services:
  kkc-portal:
    image: winnybob/kkc-3d-portal:latest
    container_name: kkc-portal
    restart: unless-stopped
    ports:
      - "5021:5021"
    volumes:
      - /mnt/KKC/kkc-3d-portal:/app/jobs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5021
