import re

viewer_file = 'public/js/viewer.js'

with open(viewer_file, 'r') as f:
    content = f.read()

# Look at this:
# [error] Material Walnut has map_kd: f744bca2-2784-4b18-9e27-5009e6b5c9e3/Walnut.jpg -> loading manually from /jobs/002/f744bca2-2784-4b18-9e27-5009e6b5c9e3/Walnut.jpg

# The path is `f744bca2-2784-4b18-9e27-5009e6b5c9e3/Walnut.jpg`.
# The mtlDir is `https://3dportal.kustomkraftcabinets.ddns.net/jobs/002/` (with a `/` at the end).
# Wait, NO.
# The URL in viewer is relative to the backend API: `/jobs/002/6ef73686...mtl` (this was a redirect or absolute path? Let's check `mtlUrl` value).
# Wait, `mtlDir` was `/jobs/002/`.
# If `map_kd` is `f744bca2-2784-4b18-9e27-5009e6b5c9e3/Walnut.jpg`, it appends it to `/jobs/002/`.
# Result: `/jobs/002/f744bca2-2784-4b18-9e27-5009e6b5c9e3/Walnut.jpg`
# Is this correct? YES. The server logs `GET /jobs/002/f744bca2.../Walnut.jpg 200`.

# IF THE TEXTURE IS LOADED, AND ASSIGNED TO `m.map`, AND `OBJLoader` GETS IT, AND THE MESH GETS IT...
# Look at the log:
# `[error] Found map on Mesh1 Group1 Model -> Walnut: http://localhost:5025/jobs/002/f744bca2-2784-4b18-9e27-5009e6b5c9e3/Walnut.jpg`
# AND the later script execution `Mesh: Mesh1 Group1 Model -> Has UVs: true -> Material: Walnut -> Has Map: true -> Color: #ffffff -> ColorSpace: srgb`

# THIS MEANS THE MATERIAL HAS THE TEXTURE!
# Then why did the user say "I dont see textures in the image you posted"?
# Let's take a look at the image I posted myself... Oh wait, the image was generated by `verify_textures.py`.
# Ah! SketchUp scales! SketchUp usually exports models in inches, but `OBJLoader` might parse them literally, leading to massive scale.
# We DID fix the scale:
# `obj.scale.set(scale, scale, scale);` where `scale` is usually `0.0254` for inches.
# What about UV scales? If the object is scaled down to 2.5%, but the texture coordinates stay the same, does the texture become tiny or massive?
# Actually, UV coordinates map from 0 to 1 across the surface, scale does not affect them.
# BUT, SketchUp sometimes exports `vt` coordinates that are huge (e.g. 100, 500) representing world space repeats rather than 0..1!
# If wrapS and wrapT are NOT set to RepeatWrapping, the texture will clamp to edge and appear as a single pixel smeared across the surface!
# Wait! I DID set `mat.map.wrapS = THREE.RepeatWrapping; mat.map.wrapT = THREE.RepeatWrapping;`
# But did I do it on the manual load, or the old one?
old_manual = """                        m.map = tex;
                        m.color.setHex(0xffffff);
                        if (m.emissive) m.emissive.setHex(0x000000);
                        if (m.specular) m.specular.setHex(0x111111);
                        m.needsUpdate = true;"""

new_manual = """                        m.map = tex;
                        m.map.wrapS = THREE.RepeatWrapping;
                        m.map.wrapT = THREE.RepeatWrapping;
                        m.color.setHex(0xffffff);
                        if (m.emissive) m.emissive.setHex(0x000000);
                        if (m.specular) m.specular.setHex(0x111111);
                        m.needsUpdate = true;"""

content = content.replace(old_manual, new_manual)

with open(viewer_file, 'w') as f:
    f.write(content)
